Gitsparty
dotnet/dotnet-docker-samples pull request #40
Opened 2017-04-02 09:11 UTC by gitsparty

Fix console command line samples

2017-04-03 13:26 UTC, drewnoakes commented on dotnetapp-current/README.md
> +Note: Before doing the follwing, make sure you are running in "Windows Container" mode. You can do this by Right Clicking the Docker app (in the System Tray) -> "Switch to Windows Containers".
Small typo here (`follwing`).

2017-04-03 13:27 UTC, drewnoakes commented on dotnetapp-dev/README.md
> +Note: Before doing the follwing, make sure you are running in "Windows Container" mode. You can do this by Right Clicking the Docker app (in the System Tray) -> "Switch to Windows Containers".
Ditto.

2017-04-03 13:27 UTC, drewnoakes commented on dotnetapp-prod/README.md
> +Note: Before doing the follwing, make sure you are running in "Windows Container" mode. You can do this by Right Clicking the Docker app (in the System Tray) -> "Switch to Windows Containers".
Ditto

2017-04-03 13:27 UTC, drewnoakes commented on dotnetapp-selfcontained/README.md
> +Note: Before doing the follwing, make sure you are running in "Windows Container" mode. You can do this by Right Clicking the Docker app (in the System Tray) -> "Switch to Windows Containers".
Ditto

2017-04-03 16:43 UTC, MichaelSimons reviewed
Thanks for the contribution.  I just have a couple minor comments.

2017-04-03 16:43 UTC, MichaelSimons commented on dotnetapp-current/README.md
> +Follow these steps to run this sample in a  Windows container.
Extra space 'a  Windows'

2017-04-03 16:43 UTC, MichaelSimons commented on dotnetapp-current/README.md
> +Note: Before doing the follwing, make sure you are running in "Windows Container" mode. You can do this by Right Clicking the Docker app (in the System Tray) -> "Switch to Windows Containers".
Consider adding a link to https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers for additional information.

2017-04-03 16:43 UTC, MichaelSimons commented on dotnetapp-current/README.md
> -dotnet run Hello .NET Core from Docker
While args are not required, the reason they were specified was to illustrate how you can pass args to the containerized app.

2017-04-03 16:43 UTC, MichaelSimons commented on dotnetapp-selfcontained/README.md
> +
nit 😃 - Unnecessary trailing blank lines.

2017-04-03 17:03 UTC, kendrahavens requested changes
Looks mostly good! Leave in the arguments for the `run` commands and fix the few typos and we'll be good to go.

2017-04-03 17:03 UTC, kendrahavens commented on dotnetapp-current/README.md
> -dotnet run Hello .NET Core from Docker
Yes, I think its a good idea to keep them in here.

2017-04-03 17:03 UTC, kendrahavens commented on dotnetapp-current/README.md
> +Note: Before doing the follwing, make sure you are running in "Windows Container" mode. You can do this by Right Clicking the Docker app (in the System Tray) -> "Switch to Windows Containers".
These are great notes to add. Thank you!

2017-04-21 15:56 UTC, MichaelSimons commented
@gitsparty, can you make the suggested edits or let us know any maybe someone else can.  Thanks

2017-07-11 21:19 UTC, MichaelSimons commented
With multi-stage builds the experience has mostly been unified between Linux and Windows.  This PR is out of date.  Closing but feel free to make a new PR as appropriate if you still see issues.

2017-07-11 21:19 UTC, closed without merging